crypto_app/urls.py
from django.urls import path
from .views import index, dashboard_view, profile_view, profile_settings_view, coin_detail_view, coin_list_view, payment_view, send_payment_review

app_name = "core"

urlpatterns = [
    path('', index, name='index'),
    path('app/coins/', coin_list_view, name='coin-list'),
    path('app/coin/<pid>/', coin_detail_view, name='coin-detail'),
    path('app/dashboard', dashboard_view, name='dashboard'),
    path('app/profile', profile_view, name='profile'),
    path("send-payment-review/<pid>/", send_payment_review, name="send-payment-review"),
    path('app/profile-settings', profile_settings_view, name='profile-settings'),
    path('app/coin/payment', payment_view, name='payment'),
]

crypto_invest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('crypto_app.urls')),
    path("", include('userauths.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path, include
from userauths import views

app_name = "userauths"

urlpatterns = [
    path('user/sign-up/', views.register_view, name= "sign-up"),
    path('user/sign-in/', views.login_view, name="sign-in"),
    path('logout', views.logout_view, name="logout"),
    path('lockscreen', views.lock_screen_view, name='lockscreen'),
    # path('activate-user/<uidb64>/<token>', views.activate_user, name="activate")
]

templates/partials/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static './dist/css/main.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>

<body>

    <div class="page-wrapper bg-dark">
        <!-- header -->
        <div class="header-wrapper">
            <header class="header flex">
                <div class="container w-full flex-1 flex">
                    <div class="header-content w-full flex-1 flex flex-col">
                        <nav class="navbar flex items-center justify-between">
                            <div class="brand-and-toggler flex items-center justify-between w-full">
                                <a href="#" class="navbar-brand flex items-center">
                                    <img src="{% static './assets/icons/site_icon.svg' %}">
                                    <span class="brand-text">BitTrade</span>
                                </a>
                                <button type="button" class="navbar-show-btn">
                                    <img src="{% static './assets/icons/menu_icon.svg' %}" />
                                </button>
                            </div>

                            <div class="navbar-list-wrapper flex items-center" style="z-index: 100;">
                                <ul class="nav-list flex items-center">
                                    <button type="button" class="navbar-hide-btn">
                                        <img src="{% static './assets/icons/close.svg' %}" />
                                    </button>
                                    <li class="nav-item">
                                        <a href="{% url "userauths:sign-up" %}" class="nav-link text-base no-wrap">Buy / Sell</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url "userauths:sign-in" %}" class="nav-link text-base no-wrap">Grow</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{% url "userauths:sign-in" %}" class="nav-link text-base no-wrap">Market</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#" class="nav-link text-base no-wrap">Business</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#" class="nav-link text-base no-wrap">Support</a>
                                    </li>
                                    
                                        
                                  

                                </ul>
                                {% if request.user.is_authenticated == False %}
                                <div class="sign-btns flex items-center">
                                    <a href="{% url 'userauths:sign-in' %}" class="btn text-base">Sign in</a>
                                    <a href="{% url 'userauths:sign-up' %}" class="btn btn-g-blue-veronica text-base">Sign up</a>
                                </div>
                                {% else %}
                                <div class="sign-btns flex items-center">
                                    <a href="{% url 'core:dashboard' %}" class="btn text-base">Dashboard</a>
                                    <a href="{% url 'userauths:logout' %}" class="btn btn-g-blue-veronica text-base">Logout</a>
                                </div>
                                {% endif %}

                            </div>
                        </nav>
                        
                        {% block content %}

                        {% endblock content %}
                        <footer class="footer">
                           
                            <div class="container">
                                <div id="google_translate_element" style="width: 0px; "></div>
                                <div class="footer-content grid">
                                    
                                    <div class="footer-item">
                                        <p class="text text-base">BitTrade, the world's leading bitcoin ATM operator,
                                            makes it so flipping easy to buy and sell bitcoin via cash, card, or bank
                                            transfer.</p>
                                        <p class="text text-base">Sign up to get the latest in BitTrade news, discounts,
                                            and more.</p>

                                        <form class="flex items-center">
                                            <div class="input-group flex items-center justify-between">
                                                <input type="text" class="input-control" placeholder="Email address" />
                                                <button type="submit"
                                                    class="input-btn flex items-center justify-center">
                                                    <img src="{% static './assets/icons/arrow_white.svg' %}" />
                                                </button>
                                            </div>
                                        </form>
                                        <p class="text text-base">&copy; 2021 BitTrade</p>
                                    </div>

                                    <div class="footer-item">
                                        <h4 class="footer-item-title text-gray text-base">Company</h4>
                                        <ul class="footer-links">
                                            <li>
                                                <a href="#" class="footer-link text-gray text-base">About</a>
                                            </li>
                                            <li>
                                                <a href="#" class="footer-link text-gray text-base">Careers</a>
                                            </li>
                                            <li>
                                                <a href="#" class="footer-link text-gray text-base">Press</a>
                                            </li>
                                            <li>
                                                <a href="#" class="footer-link text-gray text-base">News</a>
                                            </li>
                                            <li>
                                                <a href="#" class="footer-link text-gray text-base">Links</a>
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="footer-item">
                                        <h4 class="footer-item-title text-gray text-base">Privacy Policy and Terms of
                                            Services</h4>
                                        <ul class="footer-links">
                                            <li>
                                                <a href="#" class="footer-link text-gray text-base">CoinFlip Privacy
                                                    Policy</a>
                                            </li>
                                            <li>
                                                <a href="#" class="footer-link text-gray text-base">Biometrics Privacy
                                                    Policy</a>
                                            </li>
                                            <li>
                                                <a href="#" class="footer-link text-gray text-base">Financial Policy
                                                    Notice</a>
                                            </li>
                                            <li>
                                                <a href="#" class="footer-link text-gray text-base">Terms of Service</a>
                                            </li>
                                            <li>
                                                <a href="#" class="footer-link text-gray text-base">Trade Desk Terms of
                                                    Service</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </footer>
                    </div>


                    <script src="https://www.cryptohopper.com/widgets/js/script"></script>
                    <script src="{% static './app/js/script.js' %}"></script>
                    
                    <script type="text/javascript">
                        function googleTranslateElementInit() {
                          new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
                        }
                        </script>
                        
                    <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
</body>

</html>